# Generated by Django 5.1.5 on 2025-02-11 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('calories', models.FloatField()),
                ('total_fat', models.FloatField()),
                ('protein', models.FloatField()),
                ('carbohydrate', models.FloatField()),
                ('fiber', models.FloatField()),
                ('sugars', models.FloatField()),
            ],
        ),
    ]
