# Generated by Django 5.1.5 on 2025-02-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_nutrients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrients',
            name='calories',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='nutrients',
            name='carbohydrate',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='nutrients',
            name='fiber',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='nutrients',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='nutrients',
            name='protein',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='nutrients',
            name='sugars',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='nutrients',
            name='total_fat',
            field=models.CharField(max_length=32),
        ),
    ]
