# Generated by Django 5.1.5 on 2025-02-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_nutrients_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrients',
            name='calories',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nutrients',
            name='carbohydrate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nutrients',
            name='fiber',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nutrients',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='nutrients',
            name='protein',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nutrients',
            name='sugars',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nutrients',
            name='total_fat',
            field=models.FloatField(),
        ),
    ]
